// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/venice.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protos_2fvenice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protos_2fvenice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2fvenice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fvenice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protos_2fvenice_2eproto;
class VeniceMessageProto;
struct VeniceMessageProtoDefaultTypeInternal;
extern VeniceMessageProtoDefaultTypeInternal _VeniceMessageProto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::VeniceMessageProto* Arena::CreateMaybeMessage<::VeniceMessageProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class VeniceMessageProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VeniceMessageProto) */ {
 public:
  inline VeniceMessageProto() : VeniceMessageProto(nullptr) {}
  ~VeniceMessageProto() override;
  explicit PROTOBUF_CONSTEXPR VeniceMessageProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VeniceMessageProto(const VeniceMessageProto& from);
  VeniceMessageProto(VeniceMessageProto&& from) noexcept
    : VeniceMessageProto() {
    *this = ::std::move(from);
  }

  inline VeniceMessageProto& operator=(const VeniceMessageProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline VeniceMessageProto& operator=(VeniceMessageProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VeniceMessageProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const VeniceMessageProto* internal_default_instance() {
    return reinterpret_cast<const VeniceMessageProto*>(
               &_VeniceMessageProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VeniceMessageProto& a, VeniceMessageProto& b) {
    a.Swap(&b);
  }
  inline void Swap(VeniceMessageProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VeniceMessageProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VeniceMessageProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VeniceMessageProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VeniceMessageProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VeniceMessageProto& from) {
    VeniceMessageProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VeniceMessageProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VeniceMessageProto";
  }
  protected:
  explicit VeniceMessageProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kMessageIdFieldNumber = 1,
    kAckFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 messageId = 1;
  void clear_messageid();
  int32_t messageid() const;
  void set_messageid(int32_t value);
  private:
  int32_t _internal_messageid() const;
  void _internal_set_messageid(int32_t value);
  public:

  // bool ack = 2;
  void clear_ack();
  bool ack() const;
  void set_ack(bool value);
  private:
  bool _internal_ack() const;
  void _internal_set_ack(bool value);
  public:

  // @@protoc_insertion_point(class_scope:VeniceMessageProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int32_t messageid_;
    bool ack_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2fvenice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VeniceMessageProto

// int32 messageId = 1;
inline void VeniceMessageProto::clear_messageid() {
  _impl_.messageid_ = 0;
}
inline int32_t VeniceMessageProto::_internal_messageid() const {
  return _impl_.messageid_;
}
inline int32_t VeniceMessageProto::messageid() const {
  // @@protoc_insertion_point(field_get:VeniceMessageProto.messageId)
  return _internal_messageid();
}
inline void VeniceMessageProto::_internal_set_messageid(int32_t value) {
  
  _impl_.messageid_ = value;
}
inline void VeniceMessageProto::set_messageid(int32_t value) {
  _internal_set_messageid(value);
  // @@protoc_insertion_point(field_set:VeniceMessageProto.messageId)
}

// bool ack = 2;
inline void VeniceMessageProto::clear_ack() {
  _impl_.ack_ = false;
}
inline bool VeniceMessageProto::_internal_ack() const {
  return _impl_.ack_;
}
inline bool VeniceMessageProto::ack() const {
  // @@protoc_insertion_point(field_get:VeniceMessageProto.ack)
  return _internal_ack();
}
inline void VeniceMessageProto::_internal_set_ack(bool value) {
  
  _impl_.ack_ = value;
}
inline void VeniceMessageProto::set_ack(bool value) {
  _internal_set_ack(value);
  // @@protoc_insertion_point(field_set:VeniceMessageProto.ack)
}

// bytes data = 3;
inline void VeniceMessageProto::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& VeniceMessageProto::data() const {
  // @@protoc_insertion_point(field_get:VeniceMessageProto.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VeniceMessageProto::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:VeniceMessageProto.data)
}
inline std::string* VeniceMessageProto::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:VeniceMessageProto.data)
  return _s;
}
inline const std::string& VeniceMessageProto::_internal_data() const {
  return _impl_.data_.Get();
}
inline void VeniceMessageProto::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* VeniceMessageProto::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* VeniceMessageProto::release_data() {
  // @@protoc_insertion_point(field_release:VeniceMessageProto.data)
  return _impl_.data_.Release();
}
inline void VeniceMessageProto::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:VeniceMessageProto.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protos_2fvenice_2eproto
